name: escape_space
description: "Make the flame game Escape Space"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flame: ^1.23.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/buttons/previous.png
    - assets/buttons/next.png
    - assets/images/level_1.png
    - assets/options/option_1.png
    - assets/options/option_2.png
    - assets/options/option_3.png
    - assets/video/level_1_completed.mp4

